### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by RazTeve** [Swym-Pools/Swym_App#21]
Update to Google fonts: 
Luckiest Guy
Krub

**Comment by danielleolgin** [comment]
Headers/Titles use Luckiest guy (https://fonts.google.com/specimen/Luckiest+Guy)
Text use Krub (https://fonts.google.com/specimen/Krub)

Headers include:
 - "Swym" on signup and login page
 - "Savings", "Pool" and "Account" headers on each tab

Text includes everything else
