### ISSUE TITLE
 Forgot/Reset password

### ISSUE THREAD

**Issue by RazTeve** [Swym-Pools/Swym_App#25]
We need a way for users to reset passwords they may have lost.

https://stackoverflow.com/questions/20277020/how-to-reset-change-password-in-node-js-with-passport-js

**Comment by danielleolgin** [comment]
@nadirhamid here are the designs for password reset https://www.figma.com/proto/OyqfqworCJuLPynAMCNTcK/Untitled?node-id=546%3A2&scaling=min-zoom&page-id=546%3A1

**Comment by danielleolgin** [comment]
Nadir finished june 17
